Fixing installer.sh
winapps-org/winapps pull request #108
Opened 2024-05-30 21:47 UTC by Alchemi1963

Rewrote the printf lines to work nice with writing the batch script.
Rewrote the apps scanner to take relative paths (with ls) for more consistent results across
Added checks for emtpy vars so *bin* aren't accidentally written to or deleted.

2024-05-31 07:12 UTC, oskardotglobal requested changes
Thank you for this pull request. Just some minor issues

2024-05-31 07:12 UTC, oskardotglobal commented on installer.sh
> -            . "$F/info"
This is correct as is. Do not change this.

2024-05-31 07:12 UTC, oskardotglobal commented on installer.sh
> +            printf "IF EXIST \"%s\" ECHO %s >> \\\\\\\\tsclient\\home\\.local\\share\\winapps\\installed.tmp\n" "$WIN_EXECUTABLE" "$F" >> "$HOME/.local/share/winapps/installed.bat"
Those four extra backslashes are invalid from what I understand, or at least shellcheck does not like them; remove them

2024-05-31 07:12 UTC, oskardotglobal commented on installer.sh
> +        printf "RENAME \\\\\\\\tsclient\\home\\.local\\share\\winapps\\installed.tmp installed\n" >> "$HOME/.local/share/winapps/installed.bat"        # shellcheck disable=SC2140
That shellcheck directive needs to be on the next line

2024-05-31 07:12 UTC, oskardotglobal commented on installer.sh
> +        printf "RENAME \\\\\\\\tsclient\\home\\.local\\share\\winapps\\installed.tmp installed\n" >> "$HOME/.local/share/winapps/installed.bat"        # shellcheck disable=SC2140
Also, same thing with the backslashes

2024-05-31 07:14 UTC, jrevillard commented on installer.sh
> +        printf "RENAME \\\\\\\\tsclient\\home\\.local\\share\\winapps\\installed.tmp installed\n" >> "$HOME/.local/share/winapps/installed.bat"        # shellcheck disable=SC2140
There are needed... I fixed everything like this yesterday night too 
`\n` i also mandatory.

2024-05-31 07:15 UTC, jrevillard commented on installer.sh
> +            printf "IF EXIST \"%s\" ECHO %s >> \\\\\\\\tsclient\\home\\.local\\share\\winapps\\installed.tmp\n" "$WIN_EXECUTABLE" "$F" >> "$HOME/.local/share/winapps/installed.bat"
There are needed... I fixed everything like this yesterday night too

2024-05-31 07:18 UTC, oskardotglobal commented
I will just test this on my machine and report back

2024-05-31 07:30 UTC, jrevillard commented
> I will just test this on my machine and report back

I have another fix also... I did not made any MR but here is my diff: 
[installer.PATCH](https://github.com/user-attachments/files/15509914/installer.PATCH)

It's still not perfect... I have the same problem than #111 and  #110 (this later I simply removed the check as you see)

2024-05-31 07:49 UTC, LDprg commented on installer.sh
> +            printf "IF EXIST \"%s\" ECHO %s >> \\\\\\\\tsclient\\home\\.local\\share\\winapps\\installed.tmp\n" "$WIN_EXECUTABLE" "$F" >> "$HOME/.local/share/winapps/installed.bat"
Why are they needed? \\\\tsclient results in \\tsclient which seem correct to me. So why should it the double amount of backslashes?

2024-05-31 08:02 UTC, jrevillard commented on installer.sh
> +            printf "IF EXIST \"%s\" ECHO %s >> \\\\\\\\tsclient\\home\\.local\\share\\winapps\\installed.tmp\n" "$WIN_EXECUTABLE" "$F" >> "$HOME/.local/share/winapps/installed.bat"
because `\t` is also interpreted as a tabulation :smile:

2024-05-31 08:19 UTC, Alchemi1963 commented on installer.sh
> +            printf "IF EXIST \"%s\" ECHO %s >> \\\\\\\\tsclient\\home\\.local\\share\\winapps\\installed.tmp\n" "$WIN_EXECUTABLE" "$F" >> "$HOME/.local/share/winapps/installed.bat"
Yes, @jrevillard got it right.
The four backslashes got interpreted as one.
So I added four more, if the shellcheck doesn't like them the script should probably go back to using echo instead of printf or the shellcheck needs to be disabled for that line (I think that's possible? Not sure though, never used it before).

2024-05-31 08:27 UTC, oskardotglobal commented
I have a fix for the printf problem, gonna commit that rq

2024-05-31 08:29 UTC, Alchemi1963 commented
> > I will just test this on my machine and report back
> 
> I have another fix also... I did not made any MR but here is my diff: [installer.PATCH](https://github.com/user-attachments/files/15509914/installer.PATCH)
> 
> It's still not perfect... I have the same problem than #111 and #110 (this one I simply removed the check as you see)

I see you did mostly the same things and had the same issue as I in #109 :)
I did that too, but didn't commit it as the devs specifically made a commit a while back about preferring system icons instead (idk why but ok)

2024-05-31 08:30 UTC, Alchemi1963 commented
> I have a fix for the printf problem, gonna commit that rq

Out of curiosity, what is that fix?

2024-05-31 08:38 UTC, oskardotglobal commented
@Alchemi1963 

If you run a printf like
```shell
printf "%s\n" 'powershell.exe -ExecutionPolicy Bypass -File \\tsclient\home\.local\share\\winapps\ExtractPrograms.ps1 > \\tsclient\home\.local\share\winapps\detected'
```
with the argument containing backslashes in single quotes and have a first argument in double quotes then the backslashes will be interpreted literally

2024-05-31 08:38 UTC, oskardotglobal commented
No more double or triple escaping

2024-05-31 08:40 UTC, oskardotglobal requested changes
Ok, this is now ready to go once the issues mentioned by shellcheck are resolved.

2024-05-31 09:02 UTC, Alchemi1963 commented
> @Alchemi1963
> 
> If you run a printf like
> 
> ```shell
> printf "%s\n" 'powershell.exe -ExecutionPolicy Bypass -File \\tsclient\home\.local\share\\winapps\ExtractPrograms.ps1 > \\tsclient\home\.local\share\winapps\detected'
> ```
> 
> with the argument containing backslashes in single quotes and have a first argument in double quotes then the backslashes will be interpreted literally

Oh yeah, that is *much* cleaner

2024-05-31 11:02 UTC, Firelfy commented
This PR allows allows installer.sh to complete successfully for me. No more RDP connection error message.

2024-05-31 11:43 UTC, LDprg approved these changes
Thats very nice work. Thx for ever contributing.

2024-05-31 11:44 UTC, LDprg commented
pre-commit.ci autofix

2024-05-31 11:47 UTC, LDprg commented
We only need to fix shellcheck, before merging.

2024-06-08 18:15 UTC, oskardotglobal requested changes

2024-06-08 18:15 UTC, oskardotglobal commented on installer.sh
> +        echo \""$F"\" >> test
Why is this still quoted twice?

2024-06-08 18:15 UTC, oskardotglobal commented on installer.sh
> +        echo \""$F"\" >> "test"
Doesn't that just do nothing now? I think this is supposed to be a check whether F is empty

2024-06-08 18:22 UTC, LDprg commented on installer.sh
> +        echo \""$F"\" >> test
One quote is for ensuring $F is correctly accessed. \" is for the quote in the string.

2024-06-08 18:25 UTC, LDprg commented on installer.sh
> +        echo \""$F"\" >> "test"
@oskardotglobal It writes the content of $F into a test file. Wasn't sure if we need it but we need to double quote so shellcheck doesn't complain about misconceptions with the test command.

Not sure if we could remove it.

2024-06-08 18:32 UTC, oskardotglobal commented on installer.sh
> +        echo \""$F"\" >> "test"
I thought it piped into the `test` command (https://linux.die.net/man/1/test), but that makes sense too

2024-06-08 18:36 UTC, oskardotglobal commented on installer.sh
> +        echo \""$F"\" >> "test"
If I search the file there are no other occurences of `test`
I say we remove it.

2024-06-08 20:09 UTC, LDprg commented on installer.sh
> +        echo \""$F"\" >> "test"
I agree

2024-06-09 09:27 UTC, IsaacZD commented on installer.sh
> +            . "$DIR/apps/$F/info"
I'm experimenting this patch and I'm getting errors from this line. Seems $F is already absolute path in so "$DIR/apps" isn't really needed?

2024-06-09 09:28 UTC, oskardotglobal commented on installer.sh
> +            . "$DIR/apps/$F/info"
Oh, right
Thanks for mentioning it, I would've missed that

2024-06-09 09:28 UTC, oskardotglobal commented on installer.sh
> +            . "$DIR/apps/$F/info"
(We previously fixed that in another PR)

2024-06-09 09:32 UTC, oskardotglobal approved these changes
Alright, this looks ready to merge for me

2024-06-09 10:47 UTC, LDprg approved these changes
Seems good to me

2024-06-09 11:12 UTC, IsaacZD commented on installer.sh
>              . "$F/info"
@oskardotglobal Thanks for your rapid response! I didn't expect it to be updated that fast : ).
So I've played with it a bit more and seems to have fixed errors in user mode (not sure about system as I'm not planning doing that). What I did is simply:
1. Add F="$(basename "$F")" above this line so we can use "$DIR/apps/$F/info" now. This is necessary because other places are also using $F and simply remove "$DIR/apps" in this line doesn't fix other places.
2. Add F=$(echo "$F" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//') to all "while IFS= read -r F" blocks because I'm getting errors due to trailing spaces.

Not sure if these fixes apply to others though because I'm using Nixos which is quite different to other distros, so probably needs to test in other environments.

Gonna go sleep now but hope this is helpful ; )

2024-06-09 11:39 UTC, oskardotglobal commented on installer.sh
>              . "$F/info"
This is very helpful, thank you
I'm actually using Nix too, but these seem like general issues so I've commited the fix

2024-06-09 13:16 UTC, merged