Update RDPApps.reg link
winapps-org/winapps pull request #14
Opened 2023-07-15 13:11 UTC by Leonardo-DGS

2023-07-15 14:38 UTC, oskardotglobal commented
Thank you for your contribution. However, we can't merge this yet due to legal issues we're currently resolving.

2023-07-15 14:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/winapps-org/winapps?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/winapps-org/winapps?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/winapps-org/winapps?pullRequest=14) it.</sub>

2023-07-15 20:04 UTC, fbartels requested changes

2023-07-15 20:04 UTC, fbartels commented on docs/KVM.md
> +Once you finish the driver install, you will need to make some registry changes to enable RDP Applications to run on the system. Start by downloading the `RDPApps.reg` file from the WinApps repo by v
Can we make this link relative?

2023-07-16 09:58 UTC, oskardotglobal approved these changes
Looks good

2023-07-16 14:03 UTC, LDprg commented
Sure a relative link would be copied correctly when right clicking -> Copy? Because many people just copy the link that way and past it into the vm.

2023-07-16 14:59 UTC, fbartels approved these changes

2023-07-16 15:05 UTC, fbartels commented
@LDprg no, this would not work for a direct paste into curl. But the behaviour with a relative or absolute link still give the same result (a Github page). The readme also explains what do it. So while not optimal, i think there is enought guidance on what to do.

2023-07-16 18:06 UTC, Leonardo-DGS commented
> Sure a relative link would be copied correctly when right clicking -> Copy? Because many people just copy the link that way and past it into the vm.

I've tried and it works.

2023-07-16 18:16 UTC, oskardotglobal commented
Can confirm. Merging this since relicensing isn't an issue, see: https://github.com/winapps-org/winapps/discussions/11#discussioncomment-6461682

2023-07-16 18:16 UTC, merged

2023-07-16 18:17 UTC, oskardotglobal commented
@Leonardo-DGS Thank you for your contribution