Fix logging to show correct date/times
winapps-org/winapps pull request #336
Opened 2024-11-25 22:30 UTC by mindset-tk

Logging was misleading and the date/times logged to file were always the time that the app was initialized, instead of the time of the actual log entry. Issue was noted in https://github.com/winapps-org/winapps/issues/334.

2024-11-25 22:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/winapps-org/winapps?pullRequest=336) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/winapps-org/winapps?pullRequest=336) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/winapps-org/winapps?pullRequest=336) it.</sub>

2024-11-28 13:52 UTC, oskardotglobal requested changes

2024-11-28 13:52 UTC, oskardotglobal commented on bin/winapps
> +    [ "$DEBUG" = "true" ] && echo "[$(date)-$RUNID] $1" >>"$LOG_PATH"
The `RUNID` variable doesn't seem to be accessed anywhere else, so you can remove it.

2024-11-28 13:54 UTC, LDprg approved these changes

2024-11-28 18:49 UTC, mindset-tk commented on bin/winapps
> +    [ "$DEBUG" = "true" ] && echo "[$(date)-$RUNID] $1" >>"$LOG_PATH"
The run ID will aid in troubleshooting since it adds a semi unique random int to the end of the date on the log file, that remains the same across the each run of the script.  It would need to be stored in a var somewhere.

This was the apparent original purpose of declaring the $RUN var at the top of the script.

2024-11-28 19:21 UTC, oskardotglobal commented on bin/winapps
> +    [ "$DEBUG" = "true" ] && echo "[$(date)-$RUNID] $1" >>"$LOG_PATH"
Ok, that seems logical.

2024-11-28 19:22 UTC, oskardotglobal approved these changes

2024-11-28 19:22 UTC, merged