Add freerdp backend
winapps-org/winapps pull request #42
Opened 2023-09-10 18:15 UTC by LDprg

This moved from #30 to here for better way of working.

2023-10-07 17:47 UTC, oskardotglobal requested changes

2023-10-07 17:47 UTC, oskardotglobal commented on winapps/src/freerdp.rs
>                  "/d:".to_owned() + &config.rdp.domain,
You should probably use [`format!`](https://doc.rust-lang.org/std/macro.format.html) for these.
Also, you can pass `&str` to these instead of `String`, see https://github.com/oskardotglobal/winapps/blob/rewrite/winapps/src/quickemu.rs#L34-L42

2023-10-07 17:55 UTC, LDprg commented on winapps/src/freerdp.rs
>                  "/d:".to_owned() + &config.rdp.domain,
Thx, forgot about this one.

2023-10-07 18:04 UTC, LDprg commented
So I think generally the the base is finished and ready for merge. Just waiting for some reviews.

Maybe we want to change to command names (later this would we much more complicated).

2023-10-07 18:17 UTC, oskardotglobal approved these changes
Looks great.

2023-10-07 18:17 UTC, oskardotglobal commented
> Maybe we want to change to command names
We could just keep what you've called `app` as `manual`, but imo `run` would be better

2023-10-07 20:05 UTC, AkechiShiro commented
@oskardotglobal did you try and build this branch ? Or should I test it on my side ?

2023-10-07 22:46 UTC, oskardotglobal commented
Nope, I'll test this later

2023-10-07 23:20 UTC, AkechiShiro commented
I tested the build works, but there are a few issues, I noticed @LDprg

- `winapps-cli check` ![image](https://github.com/winapps-org/winapps/assets/14914796/dfb4e9c6-f62e-4036-a8c3-9bf6f00a25b0)
- I tried a few commands, but they seemed to fail if `XDG_CONFIG_HOME` wasn't defined, we should automatically fallback on `$HOME/.config`

2023-10-08 07:07 UTC, oskardotglobal commented
@AkechiShiro the latter is included in #26

2023-10-08 07:31 UTC, LDprg commented
@AkechiShiro The first one is that winapps doesnt disable the freerdp output (which containst alot of unnecessary warings). I will investigate into this.

2023-10-08 10:39 UTC, LDprg commented
@AkechiShiro did you test it with the generated quickemu from #26? I am not sure if we need a port forwarding from the guest to host to make rdp communication working per default.

2023-10-08 11:20 UTC, AkechiShiro commented
@LDprg no I removed all the previous files to test cleanly but I understand that there is no quickemu get and VMs files

2023-10-08 12:47 UTC, oskardotglobal commented
@LDprg I'll test it

2023-10-09 08:33 UTC, LDprg commented
So finally I fixed the log outputs of freerdp causing unessecary warnings to be shown. Later we could redirect its output to some log files, however this will be in a sperate PR (just want this get through as fast as possible). 

Furthermore I fixed some minor issues after the merge of #26 and renamed the app command to run.
@oskardotglobal can you review this so I can merge.

2023-10-09 09:09 UTC, oskardotglobal requested changes
Looks good otherwise

2023-10-09 09:09 UTC, oskardotglobal commented on winapps/src/freerdp.rs
> +                        "-wallpaper",
Any reason why you add the `-wallpaper` flag here and not if the app isn't given?

2023-10-09 13:35 UTC, LDprg commented
@oskardotglobal I removed it. Can you approve so I can merge?

2023-10-09 15:39 UTC, oskardotglobal approved these changes
Looks good.

2023-10-09 15:39 UTC, merged