feat: error handling
winapps-org/winapps pull request #48
Opened 2023-10-07 22:45 UTC by oskardotglobal

All those `.expect`s and nested match statements were bugging me, so I've written a custom error handler.

Basically, I've written 2 macros, which do the following:
- `unwrap_or_panic!` & `unwrap_or_exit!` - Unwrap either an Option or a Result. Log the error of the result if it exists + further context with `format!` syntax support
- `error!` & `error_from!` - Construct a `WinappsError` from an existing error and / or a message. This is mostly used to return values from functions, but you can still call `panic` and `exit` on it for the functionality of the 2 macros above 

I've also documented all of them and all the structs, enums and traits I used.
This also includes the commits from #26, so that has to be merged first.

2023-10-09 06:50 UTC, oskardotglobal commented
This is ready for review now with #26 being merged

2023-10-09 16:54 UTC, LDprg commented
@oskardotglobal seems like something messed up with your repo, because it for example readds the quickemu installer script.

2023-10-09 16:58 UTC, oskardotglobal commented
Yeah, gotta merge first

2023-10-09 17:12 UTC, oskardotglobal commented
Ok, this is fully up-to-date now.

2023-10-09 19:20 UTC, LDprg requested changes
Some minor code parts did get lost, otherwise great work.

2023-10-09 19:20 UTC, LDprg commented on winapps/src/quickemu.rs
> +    );
Is there a reason you removed the trim function?

2023-10-09 19:20 UTC, LDprg commented on winapps/src/quickemu.rs
> +            .args([
Seems like you forgot the ignore msrs

2023-10-10 12:24 UTC, oskardotglobal commented on winapps/src/quickemu.rs
> +    );
Nope, I missed that

2023-10-10 13:36 UTC, oskardotglobal commented
Ok I've made some more changes; I've fully removed the `unwrap_or_exit` and `unwrap_or_panic` functions because them having the same name as the macros was kind of stupid because the IDE would automatically import those instead of the macros
I've replaced them with the `into_error` macro which just wraps the result in a function that does some type magic and returns a `Result<T, WinappsError>`. I've also documented all my changed

2023-10-10 15:39 UTC, LDprg requested changes
Almost finished.

2023-10-10 15:39 UTC, LDprg commented on winapps/src/quickemu.rs
> +    );
Still not the same, you only trim config.vm.name.

2023-10-10 17:22 UTC, oskardotglobal commented
there we go

2023-10-10 19:52 UTC, LDprg approved these changes
This is now ready.

2023-10-10 19:52 UTC, merged