Several Fixes (freerdp4 command line, able to be run on multiple distros, fixing a typo)
winapps-org/winapps pull request #87
Opened 2024-04-20 20:32 UTC by GreatNovaDragon

… to install all officially supported apps in one go, also fix a typo

This PR contains Several Fixes.
With FreeRDP3, the command line interface has been reworked, making the old one non-compatible.

Several of the commands given here made the baseline assumption that it is run on Ubuntu, like the assumption the command is always named "xfreerdp", when at least under Arch it is xfreerdp3. So the check for that is also in, and the option to supply an own command there. 
Or the base assumption that bc is installed (it isnt under arch)

It also adds an convenience argument to setup all officially supported apps at once. 

Also, there was an typo for the Windows launcher, telling us it belonged to "Micorosoft" instead of Microsoft

2024-04-20 20:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/winapps-org/winapps?pullRequest=87) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/winapps-org/winapps?pullRequest=87) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/winapps-org/winapps?pullRequest=87) it.</sub>

2024-04-20 20:40 UTC, GreatNovaDragon commented
Should fix #81 
Might fix #79 
Affects #69 in that you would be able to just select the commands for sdl-freerdp3 and wlfreerdp3 (even if their support for RemoteApp is not existent right now)

2024-04-21 19:51 UTC, oskardotglobal commented
Hello, thank you for your contribution.
So far this looks good, but I will have to test it on my machine

2024-04-21 19:52 UTC, oskardotglobal commented
@LDprg Thoughts?

2024-04-21 20:03 UTC, LDprg commented
Seems very good to me, a lot of great refinements. Thx for the contribution.

@oskardotglobal have you tested it?

However we also should make a proper review. (I will do one propably by the end of this week, if nobody does before)

2024-04-21 20:11 UTC, LDprg commented
@oskardotglobal What is about our licence issue? Are we even permitted to merge this pr.

2024-04-21 20:45 UTC, oskardotglobal commented
> @oskardotglobal What is about our licence issue? Are we even permitted to merge this pr.

Well, we're technically not allowed to redistribute or modify winapps in any way, but given that fmstrat isn't going to do anything about it, we're fine. Also, as the PR's author has signed the CLA its changes fall under the GPLv3 license, so at least that part is all clear

2024-05-05 09:38 UTC, LDprg requested changes
Great work! This improves code quality a lot and has many small improvment!

Just two small changes and we are ready to merge. Thx.

2024-05-05 09:38 UTC, LDprg commented on bin/winapps
> +if [ -z "${FREERDP_COMMAND}" ]; then
We still should check whether the freerdp command is available and print a message

2024-05-05 09:38 UTC, LDprg commented on installer.sh
> +if ! command -v bc &> /dev/null
Do we really need to check if bc is installed? We like use it only in [here](https://github.com/winapps-org/winapps/blob/152a92412badea5e366c918be1cebd142624e377/install/inquirer.sh#L142), so we might just search for an alternative implementation without bc.

2024-05-05 12:30 UTC, LDprg requested changes

2024-05-05 12:30 UTC, LDprg commented on README.md
>  ## Shout outs
The formatting of this seems a bit messed up. (wrong code block)

2024-05-05 12:57 UTC, GreatNovaDragon commented on bin/winapps
> +if [ -z "${FREERDP_COMMAND}" ]; then
How this basic check suffices

2024-05-05 12:58 UTC, GreatNovaDragon commented on installer.sh
> +if ! command -v bc &> /dev/null
I wont dare to touch what i dont understand, someone else has to do that.

2024-05-05 16:25 UTC, LDprg approved these changes
Seems good to me.

@oskardotglobal @AkechiShiro Can you add a a quick review so we can merge this.

2024-05-05 17:57 UTC, oskardotglobal approved these changes
Looks good

2024-05-05 23:35 UTC, AkechiShiro approved these changes
Did a quick review, LGTM, would need to test this at a later time to check if it's all working properly

2024-05-10 08:27 UTC, LDprg commented
@AkechiShiro have you tested this pr?

I would like to merge this as soon as possible (of course if tested properly).

2024-05-12 14:04 UTC, AkechiShiro commented
I haven't found the time to do so sorry @LDprg

Would you be able to test it ?

2024-05-12 18:05 UTC, LDprg commented
I am also quite busy @AkechiShiro, not sure when I can test this. @oskardotglobal maybe you could take a look?

I would suggest anyone testing first just reports their find here. The worst (or best ;-) ) that could happen is that we have multiple reports at the same time.

2024-05-14 02:15 UTC, AkechiShiro commented
It's bit annoying to test we need to setup a W11 VM manually using KVM no ?

2024-05-14 06:15 UTC, AkechiShiro commented
Maybe I'm doing something wrong but running the installer.sh script shows there might be syntax errors : 
![image](https://github.com/winapps-org/winapps/assets/14914796/8b877302-e5a5-4079-b150-f6feac176ddf)

Can you test the script please ? @GreatNovaDragon ?

2024-05-14 06:53 UTC, oskardotglobal commented
@AkechiShiro you can always use quickemu to set up the VM
I will see if I can get this to work on my Fedora machine too

2024-05-14 07:48 UTC, AkechiShiro commented
Ran into this issue : https://github.com/quickemu-project/quickemu/issues/686

2024-05-14 08:28 UTC, AkechiShiro commented
My laptop is rebooting when I run a VM inside a VM wasn't expecting this one...

I'll need to test on another laptop running natively ArchLinux, I will be able to most likely in 2 weeks.

2024-05-14 08:51 UTC, LDprg commented
I will start writing a docker guide at some point for the legacy winnapps (and code for the rewrite). Docker should work prevent most of the issue with quickemu (because it is specifically build for portability and windows).

2024-05-14 09:02 UTC, oskardotglobal commented
Yeah, I'm also kinda fed up with quickemu
Using Docker will help here

2024-05-14 16:35 UTC, oskardotglobal commented
Alright, I'm gonna test it right now

2024-05-14 17:41 UTC, oskardotglobal commented
Ok, so I've caught a syntax error which caused me to not be able to run the script, but I've fixed that

2024-05-14 17:57 UTC, oskardotglobal commented
Unless anyone else has anything to say, I say this is ready to merge

2024-05-14 23:36 UTC, AkechiShiro commented
Thanks a lot @oskardotglobal and sorry for not having been able to wholefully test it

2024-05-15 08:15 UTC, merged