Add docker documentation for legacy winnapps
winapps-org/winapps pull request #94
Opened 2024-05-14 09:39 UTC by LDprg

Docker seems a better option for hosting the vm.

Thid Pr adds documentation on how to use docker with legacy winnapps.

2024-05-14 17:58 UTC, oskardotglobal commented
This is my compose file, in case you need it
```yaml
name: "winapps"

volumes:
  data:

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "core11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - data:/storage
```

2024-05-14 17:59 UTC, oskardotglobal commented
The only step I had to take was to manually install the .reg file, but that can be automated

2024-05-15 04:08 UTC, LDprg commented
The only change I would make is to set privileged to true and remove the device/capp_add section. There could be some trouble about permissions if not done so (on my system for example docker wasn't able to access my network interface). It would also simplify gpu passthrough (since devices do not need to be listed twice) at the cost of some not that important security.

2024-05-15 08:08 UTC, oskardotglobal commented
Make sure to mention that the RDP_IP has to be set to `localhost` or `127.0.0.1` (which might lead to better compatibility) in the config explicitely

2024-05-15 08:11 UTC, oskardotglobal commented
Also, we might wanna use bind mounts instead of named volumes by default

2024-05-15 11:33 UTC, LDprg commented
> Also, we might wanna use bind mounts instead of named volumes by default

I feel like we should do it the other way around. Use volumes as default and mention bind mounts (or maybe even recommend). Since Volumes are more independent and easier to setup on a just works system.

2024-05-15 12:01 UTC, oskardotglobal commented
My reason behind bind mounts would be to allow access to the guest's fs easily

2024-05-15 12:01 UTC, oskardotglobal commented
or wait, the mount contains a disk image, doesn't it
yeah then volumes are better

2024-05-24 04:16 UTC, LDprg commented
In general this is ready for review. I will also do a quick rebase later.

2024-05-24 09:08 UTC, oskardotglobal requested changes
Looks mostly good

2024-05-24 09:08 UTC, oskardotglobal commented on docs/docker.md
> +The easiest way to setup a windows vm is by using docker compose. Just create a `docker-compose.yml` with following content:
The preferred name for the compose file is `compose.yaml` now, see https://docs.docker.com/get-started/08_using_compose/

2024-05-24 09:08 UTC, oskardotglobal commented on docs/docker.md
> +The easiest way to setup a windows vm is by using docker compose. Just create a `docker-compose.yml` with following content:
I see you're recommending podman as the runtime here, then we should definitely call the file `compose.yaml`

2024-05-24 09:08 UTC, oskardotglobal commented on docs/docker.md
> +Since docker manages the dependencies of the container automatically you only need to install docker or podman itself. (Podman is recommended because of the faster container startup times. Note that
For compose to work with podman the podman socket has to be enabled which isn't the case by default on most distros

2024-05-24 09:08 UTC, oskardotglobal commented on docs/docker.md
> +Note: Older versions than Windows 10 are not officially supported. However they might still work with some additional tuning.
Use a callout here

2024-05-24 09:08 UTC, oskardotglobal commented on docs/docker.md
> +    privileged:true
Is there a special character here that shouldn't be? The github web editor shows a `^M` here

2024-05-24 09:08 UTC, oskardotglobal commented on docs/docker.md
> +      VERSION: "win11"
I think we should ship tiny11 by default

2024-05-24 09:08 UTC, oskardotglobal commented on docs/docker.md
> +Since docker manages the dependencies of the container automatically you only need to install docker or podman itself. (Podman is recommended because of the faster container startup times. Note that
Also, maybe link the official docker/podman installation guides

2024-05-24 09:38 UTC, LDprg commented on docs/docker.md
> +    privileged:true
I wasnt able to find this character. On my system the we editor just shows everything fine.

2024-05-24 16:18 UTC, LDprg commented on docs/docker.md
> +    privileged:true
Ah ok opened on another device and got that char visible. Fixed

2024-05-24 16:19 UTC, LDprg commented
All stuff should be fixed

2024-05-25 06:24 UTC, oskardotglobal approved these changes
Looks good.

2024-05-25 06:24 UTC, merged