Fix libvirt group detection and program calling
winapps-org/winapps pull request #97
Opened 2024-05-23 14:38 UTC by LDprg

Fixes for #95. Solves wrong invert when detecting the libvirt group. And fixed a wrong argumentwhen callibg freerdp.

2024-05-23 14:42 UTC, LDprg commented
@oskardotglobal I did only write this on the go, so I couldn't test it.

2024-05-24 07:15 UTC, jrevillard commented
Hello,

Do you finally tacle xfreerdp v2 or v3 ?.... You cannot support both simply as the syntax completely changed. In this MR, a move to v3 was done: https://github.com/winapps-org/winapps/pull/87 ... and here you go back to v2....

Best,
Jerome

2024-05-24 08:58 UTC, oskardotglobal requested changes
Yeah, @jrevillard is right
That program: syntax is needed for freerdp3, do not remove it

2024-05-24 08:58 UTC, oskardotglobal commented on bin/winapps
> -	$FREERDP_COMMAND ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /scale:${RDP_SCALE} +auto-reconnect +home-drive -wallpaper +dynamic-resolution ${MULTI_FLAG} /app:program:"explorer
This shouldn't be changed

2024-05-24 08:58 UTC, oskardotglobal commented on bin/winapps
> -		$FREERDP_COMMAND ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /scale:${RDP_SCALE} +auto-reconnect +clipboard +home-drive -wallpaper +dynamic-resolution ${MULTI_FLAG} /wm-class:
Same thing here

2024-05-24 08:58 UTC, oskardotglobal commented on bin/winapps
> -		$FREERDP_COMMAND ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /scale:${RDP_SCALE} +auto-reconnect +clipboard +home-drive -wallpaper +dynamic-resolution ${MULTI_FLAG} /wm-class:
and here

2024-05-24 08:59 UTC, oskardotglobal commented
> Hello,
> 
> Do you finally tacle xfreerdp v2 or v3 ?.... You cannot support both simply as the syntax completely changed. In this MR, a move to v3 was done: #87 ... and here you go back to v2....
> 
> Best, Jerome

Just a small issue, this is why we review PRs
This of course will not be changed, we will be staying with freerdp3

2024-05-24 09:17 UTC, LDprg commented on bin/winapps
> -	$FREERDP_COMMAND ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /scale:${RDP_SCALE} +auto-reconnect +home-drive -wallpaper +dynamic-resolution ${MULTI_FLAG} /app:program:"explorer
whops forgot abor v2 v3. Will revert

2024-05-24 09:18 UTC, LDprg commented
We might want to use a flag to switch between v2 and v3. Or we set v3 as official requirement, which is properly documented.

2024-05-24 16:19 UTC, LDprg commented
I included the libvirt fix in the refactoring pr #98. If it gets merged this is not needed

2024-05-25 06:25 UTC, oskardotglobal commented
Then we can close this PR, right?

2024-05-25 07:43 UTC, closed without merging

2024-05-25 07:44 UTC, LDprg commented
This is taken over by #98